// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnFvh0_HpfOOSgcMSLcpCa-XzEcs1_aDw',
    appId: '1:1021222142700:web:f2c726b10f60665c595bc9',
    messagingSenderId: '1021222142700',
    projectId: 'chat-app-5b89c',
    authDomain: 'chat-app-5b89c.firebaseapp.com',
    storageBucket: 'chat-app-5b89c.appspot.com',
    measurementId: 'G-JQQGQLSZN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-q5UsCEmIIwOPX3Kwhf85qjhiuob3O0Q',
    appId: '1:1021222142700:android:691dcfa6d89f131f595bc9',
    messagingSenderId: '1021222142700',
    projectId: 'chat-app-5b89c',
    storageBucket: 'chat-app-5b89c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDxmRtgS_6HGOF6NcDCf9BsRMKP4q--0c',
    appId: '1:1021222142700:ios:55fae105ff16f40e595bc9',
    messagingSenderId: '1021222142700',
    projectId: 'chat-app-5b89c',
    storageBucket: 'chat-app-5b89c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDxmRtgS_6HGOF6NcDCf9BsRMKP4q--0c',
    appId: '1:1021222142700:ios:e6c7785fbcbb0651595bc9',
    messagingSenderId: '1021222142700',
    projectId: 'chat-app-5b89c',
    storageBucket: 'chat-app-5b89c.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
